import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke} from '@tauri-apps/api/core';
import './style.css';
type Settings={enabled:boolean;edge:string;width:number;sensitivity:number;inverted:boolean};
type Feedback={volume:number;change:number;label:string};
type Status={settings:Settings;input:string;volume:number|null;error:string|null;x:number;y:number;contacts:number;frames:number;feedback:Feedback|null};
function App(){const [status,setStatus]=useState<Status|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{let live=true;const refresh=()=>invoke<Status>('get_status').then(s=>{if(live)setStatus(s)}).catch(()=>{if(live)setError('Open the desktop app with npm run tauri dev to connect to your trackpad.');});refresh();const t=setInterval(refresh,300);return()=>{live=false;clearInterval(t)}},[]);
async function update(p:Partial<Settings>){if(!status||busy)return;setBusy(true);try{await invoke('save_settings',{settings:{...status.settings,...p}});setStatus(await invoke<Status>('get_status'));setError('')}catch(e){setError(String(e))}finally{setBusy(false)}}
const s=status?.settings;
return <main><header><span className="brand">◩ EdgeVolume</span><span className="tag">MAC PROTOTYPE · 0.1</span></header><section className="intro"><div><p className="eyebrow">A SMALLER WAY TO TURN IT UP</p><h1>Volume, at your fingertips.</h1><p>Slide one finger along the physical edge of your trackpad.<br/>Up gets louder. Down gets quieter.</p></div><button disabled={!status||busy||status.input!=='Listening'} className={s?.enabled?'toggle on':'toggle'} onClick={()=>update({enabled:!s?.enabled})}>{s?.enabled?'Enabled':'Enable gestures'} <span>●</span></button></section><section className="body"><div className="visual"><div className="trackpad"><div className={'edge '+(s?.edge==='left'?'left':s?.edge==='both'?'both':'right')} style={{'--width':`${(s?.width??.08)*100}%`} as React.CSSProperties}/>{!!status?.contacts&&<span className="finger" style={{left:`${status.x*100}%`,bottom:`${status.y*100}%`}}/>}<span className="tracklabel">YOUR TRACKPAD</span></div><div className="volume"><span>Output volume</span><strong>{status?.volume!=null?`${Math.round(status.volume*100)}%`:'Unavailable'}</strong></div><progress max="1" value={status?.volume??0}/><p className="hint">Start inside the green strip. Lift your finger to end.<br/>Two or more fingers cancel the gesture.</p></div><div className="controls"><label>Active edge</label><div className="segments">{['left','right','both'].map(edge=><button disabled={!s||busy} className={s?.edge===edge?'selected':''} key={edge} onClick={()=>update({edge})}>{edge}</button>)}</div><label htmlFor="width">Edge width <b>{Math.round((s?.width??.08)*100)}%</b></label><input id="width" type="range" min="3" max="20" value={(s?.width??.08)*100} disabled={!s||busy} onChange={e=>update({width:Number(e.target.value)/100})}/><label htmlFor="sensitivity">Sensitivity <b>{(s?.sensitivity??1).toFixed(2)}×</b></label><input id="sensitivity" type="range" min=".25" max="2" step=".05" value={s?.sensitivity??1} disabled={!s||busy} onChange={e=>update({sensitivity:Number(e.target.value)})}/><label className="check"><input type="checkbox" checked={s?.inverted??false} disabled={!s||busy} onChange={e=>update({inverted:e.target.checked})}/> Reverse direction</label><button className="preview" disabled={!status} onClick={()=>invoke('preview_feedback').catch(e=>setError(String(e)))}>Preview volume indicator</button><div className="status"><span className={status?.frames?'dot live':'dot'}/><div><strong>{status?.input??'Desktop engine disconnected'}</strong><small>{status?.frames?`${status.frames} contact frames received`:'Touch your trackpad to verify input.'}</small></div></div></div></section>{(error||status?.error)&&<p role="alert" className="error">{error||status?.error}</p>}<footer>Experimental input adapter · Gestures start paused on every launch.<br/>This build observes touch input; cursor motion and system gestures can still occur.</footer></main>}
function VolumeOverlay(){
 const [feedback,setFeedback]=useState<Feedback|null>(null);
 useEffect(()=>{document.documentElement.classList.add('overlay-page');let live=true;
 const refresh=()=>invoke<Feedback|null>('get_feedback').then(f=>{if(live)setFeedback(f)}).catch(()=>{});
 refresh();const timer=setInterval(refresh,80);return()=>{live=false;clearInterval(timer)}},[]);
 const percent=Math.round((feedback?.volume??0)*100);
 return <div className="volume-overlay" role="status" aria-live="polite"><div className="overlay-top"><span className="speaker">{feedback?.label==='Increasing'?'↑':feedback?.label==='Decreasing'?'↓':'◩'}</span><div><small>EDGEVOLUME</small><div className="overlay-label">{feedback?.label??'Current volume'}</div></div><strong>{percent}<span>%</span></strong></div><progress max="100" value={percent}/></div>;
}
createRoot(document.getElementById('root')!).render(new URLSearchParams(window.location.search).has('overlay')?<VolumeOverlay/>:<App/>);
